config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers, shallow: true
  end

  root to: 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, required: true
  belongs_to :author, class_name: "User"

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :author, class_name: "User"

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions, foreign_key: "author_id", dependent: :destroy
  has_many :answers, foreign_key: "author_id", dependent: :destroy

  def author_of?(post)
    id == post&.author_id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :find_question, only: [:create, :destroy]

  def show
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.author_id = current_user.id

    if @answer.save
      redirect_to @question, notice: 'Answer was successfully created'
    else
      @question.reload
      render "questions/show"
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    if current_user.author_of?(@answer)
      @answer.destroy
      redirect_to question_path(@answer.question), notice: "Your question was successfully deleted."
    else
      redirect_to question_path(@answer.question)
    end
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  helper_method :answer

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:show, :destroy, :edit, :update]

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new(question: @question)
  end

  def edit
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.author_id = current_user.id

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy
      redirect_to questions_path, notice: 'Your question was successfully deleted.'
    else
      redirect_to questions_path
    end
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/nav' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.slim
p= link_to 'Ask question', new_question_path

- @questions.each do |question|
  p= link_to question.title, question

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.submit 'Ask'

app/views/questions/show.html.slim
h1= @question.title
p= @question.body

- if current_user&.author_of?(@question)
  p = link_to 'Delete question', question_path(@question), method: :delete

= render 'shared/errors', resource: @answer

= form_with model: [@question, @answer], local: true do |f|
  = f.label :body, 'Your answer'
  = f.text_area :body
  = f.submit 'Answer'

- @question.answers.each do |answer|
  li= answer.body
  - if current_user&.author_of?(answer)
    p = link_to 'Delete answer', answer_path(answer), 'turbo_method': :delete

app/views/shared/_errors.html.slim
-  if resource&.errors.present?
   b= "#{resource.errors.count} error(s) detected: "
   ul
     -resource.errors.full_messages.each do |message|
       li= message

app/views/shared/_nav.html.slim
nav class="navbar navbar-light bg-light"
  span class="navbar-text"
    - if signed_in?
      p class="nav user"
      ' Welcome, #{current_user.email} 
      =link_to('Log out', destroy_user_session_path, method: :delete)